// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvRdSTy1tNvQzFCkfpvg-jaMNz_UvW3UQ',
    appId: '1:854352686169:web:1d3ab108433d83abc9d548',
    messagingSenderId: '854352686169',
    projectId: 'melomix-53081',
    authDomain: 'melomix-53081.firebaseapp.com',
    storageBucket: 'melomix-53081.appspot.com',
    measurementId: 'G-650FYCBFT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MqcnjJh-MnvIRMy0KChwnduPv7sy1tk',
    appId: '1:854352686169:android:a7711e2f5255ecd6c9d548',
    messagingSenderId: '854352686169',
    projectId: 'melomix-53081',
    storageBucket: 'melomix-53081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHAAjhk5mFr7mvAfHUj9jU6nlFwddBX0',
    appId: '1:854352686169:ios:79029dde6f4ac794c9d548',
    messagingSenderId: '854352686169',
    projectId: 'melomix-53081',
    storageBucket: 'melomix-53081.appspot.com',
    iosBundleId: 'com.example.melomix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuHAAjhk5mFr7mvAfHUj9jU6nlFwddBX0',
    appId: '1:854352686169:ios:a8dbadc9f15a3d10c9d548',
    messagingSenderId: '854352686169',
    projectId: 'melomix-53081',
    storageBucket: 'melomix-53081.appspot.com',
    iosBundleId: 'com.example.melomix.RunnerTests',
  );
}
